### ISSUE TITLE
CentOS 7 state doesn't apply

### ISSUE THREAD

**Issue by BrianSidebotham** [salt-formulas/salt-formula-isc-dhcp#1]
For RHEL7 and CentOS7 the configuration data is in the same location (`/etc/dhcp`) as it is for Debian, but the defaults are not filled in.

Therefore the `state.apply` fails with the example pillar in the docs on RHEL and CentOS 7 as there are no configuration file locations defined.

You can fix this in the pillar:

```yaml
isc_dhcp:
  server:
    enabled: true
    config_dir: /etc/dhcp
    dhcpd_config: /etc/dhcp/dhcpd.conf
    hosts_config: /etc/dhcp/dhcpd.hosts
    subnets_config: /etc/dhcp/dhcpd.subnets
```

But it's better to fix it in the defaults.
